-- Table: api_direcciones.td_direcciones

-- DROP TABLE IF EXISTS api_direcciones.td_direcciones;

CREATE TABLE IF NOT EXISTS api_direcciones.td_direcciones
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    calle character varying(200) COLLATE pg_catalog."default" NOT NULL,
    colonia character varying(200) COLLATE pg_catalog."default" NOT NULL,
    municipio character varying(200) COLLATE pg_catalog."default" NOT NULL,
    numero integer NOT NULL,
    cp character varying(200) COLLATE pg_catalog."default" NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    fecha_modificacion timestamp with time zone,
    fecha_creacion timestamp with time zone,
    CONSTRAINT td_direcciones_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS api_direcciones.td_direcciones
    OWNER to postgres;

INSERT INTO api_direcciones.td_direcciones(calle, colonia, municipio,numero,cp, activo, fecha_modificacion, fecha_creacion)
VALUES ('flores','Venustiano Carranza','CDMX', 21,'04640', true, '2022-05-02 00:00:00', '2024-05-03 00:00:00');